mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('portfolio.urls', namespace="portfolio")),
    url(r'^admin/', admin.site.urls),
]

mysite/portfolio/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    url(r'^self-help/$', views.self_help, name='self-help'),

]

mysite/portfolio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/portfolio/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'portfolio/home.html', context=None)

def self_help(request):
    return render(request, 'portfolio/self-help.html', context=None)

mysite/portfolio/templates/portfolio/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Home </title>

    <!-- Twitter Bootstrap3 Style Sheet -->
    <link href="{% static 'portfolio/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- AngularJS Import -->
    <script src="{% static 'portfolio/js/angular.min.js' %}"></script>

</head>

<body>
        <nav class="navbar navbar-light bg-faded">
            <a class="navbar-brand" href="{% url 'portfolio:home' %}">S.B.S</a>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="{% url 'portfolio:home' %}">Home</a></li>
            </ul>
        </nav>

    <div class="container">

        {% block content %}

        {% endblock %}

<footer class="footer">
    <div class="pull-right">
        <p class="text-muted">Updated: 6/2016</p>
    </div>
</footer>

    </div> <!-- End Container -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->

</body>
</html>

mysite/portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="hidden-sm col-md-4"  style="background-image:url(); padding-top:55px;">
            <img src="{% static 'portfolio/img/cathedral-of-learning.jpg' %}" class="img-responsive" alt="Responsive image">
        </div>
        <div class="col-md-8">
            <div class="page-header">
                <h1>Scott Schretzenmaier</h1>
                <ul class="list-inline">
                <li><strong>Email: </strong><a href="mailto:schretzy929@gmail.com">schretzy929@gmail.com</a></li>
                <li><strong>Location: </strong>Pittsburgh, PA</li>
            </ul>
            </div>

            <h3>ISDR Systems Analyst</h3>
            <h4>University of Pittsburgh Medical Center</h4>
            <h4><small>July/2014 - Present</small></h4>

            <p class="lead">A two-year leadership development rotational program designed for its candidates to
                develop both technical and operational insight</p>

            <p><strong>UNIX Services</strong> <small>(1/16 – Present)</small></p>
            <ul>
                <li>Served as Systems Engineer managing IBM’s
                    AIX 6 and RHEL 6 operating systems</li>
                <li>Deployed discovery agent across 1700 AIX and RHEL servers </li>
                <li>Scripted Bash and KornShell processes to automate manual tasks  </li>
            </ul>

            <p><strong>Enterprise Systems Management</strong> <small>(7/15 – 1/16)</small></p>
            <ul>
                <li>Technical lead on central IT data warehousing project </li>
                <li>Lead demos and presentations on data warehouse’s structure and data</li>
                <li>Configured and created interactive Splunk management reports and dashboards</li>
            </ul>
            <p><strong>Enterprise Architecture</strong> <small>(1/15 – 7/15)</small></p>
            <ul>
                <li>Created a new standardized application selection process using Microsoft CRM </li>
                <li>Migrated application statistics and data using C# scripts</li>
                <li>Assisted in a POC for the application archiving process</li>
            </ul>
            <p><strong>Corporate Service Desk</strong> <small>(7/14 – 1/15)</small></p>
            <ul>
                <li>Full stack development of the department’s web based knowledge management tool</li>
                <li>Designed and implemented the SQL database for UPMC’s Self Help tool </li>
                <li>Worked as liaison between management and agents to map application requirements</li>
            </ul>

        </div>


    </div> <!-- End Row-->

    <div class="row">

        <div class="col-md-8 col-md-push-4">
            <h3>ISD Summer Associate</h3>
            <h4>University of Pittsburgh Medical Center</h4>
            <h4><small>June/2013 - August/2013</small></h4>
             <p class="lead">A summer internship between my college junior and senior year</p>
            <p><strong>E Record Custom App Development</strong></p>
            <ul>
                <li>Designed and developed web based tool for administering support for a hierarchy of questions</li>
                <li>Actively participated in the team’s new agile scrum software development process </li>
                <li>Participated in numerous interviews for open Software Engineer position with team</li>
            </ul>
        </div>

        <div class="col-md-4 col-md-pull-8">
            <h2 class="text-center">Side Projects</h2>

            <div class="panel panel-info">
              <div class="panel-heading">
                  <a href="{% url 'dynoquiz:signin'">Quizilla </a>
                  <span class="pull-right">6/16</span>
              </div>
              <div class="panel-body">
                A Python/Django + Angular web app that allows users to login,
                  create, take and share quizzes with other users.
              </div>
            </div>

            <div class="panel panel-info">
              <div class="panel-heading">
                  <a href="/self-help">ServiceBaseV</a>
                  <span class="pull-right">1/15</span>
              </div>
              <div class="panel-body">
                A .Net web application that was used by UPMC's service desk to store/manage knowledge
                  as well as track known company issues. The backend was used as the backbone to UPMC's
                  Self Help site along with most of the front end design.
              </div>
            </div>

        </div>
    </div>
    <div class="row">
        <h2 class="text-center">Technical Skills</h2>
        <div class="col-md-4">
            <!-- Skills -->
            <strong>Languages:</strong>
            <ul class="list-unstyled">
                <li>
                    Python
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">70% Complete (success)</span>
                      </div>
                    </div>
                </li>
                <li>
                    SQL
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">70% Complete (success)</span>
                      </div>
                    </div>
                </li>
                <li>
                    JavaScript/jQuery
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                        <span class="sr-only">70% Complete (success)</span>
                      </div>
                    </div>
                </li>
                <li>
                    Java
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">60% Complete (success)</span>
                      </div>
                    </div>
                </li>
            </ul>

            <p><strong>Others Languages:</strong></p>
            <ul class="list-inline">
                <li>Bash</li>
                <li>KornShell</li>
                <li>PHP</li>
                <li>Ruby</li>
                <li>VBA</li>
                <li>HTML</li>
                <li>CSS</li>
            </ul>


        </div>

        <div class="col-md-4">
            <!-- Skills -->
            <strong>Frameworks:</strong>
            <ul class="list-unstyled">
                <li>Django</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete (success)</span>
                      </div>
                    </div>
                <li>AngularJS</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                        <span class="sr-only">60% Complete (success)</span>
                      </div>
                    </div>
                <li>Bootstrap</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete (success)</span>
                      </div>
                    </div>
                <li>Django Rest Framework</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                        <span class="sr-only">60% Complete (success)</span>
                      </div>
                    </div>
            </ul>

            <p><strong>Others Frameworks:</strong></p>
            <ul class="list-inline">
                <li>.Net</li>
                <li>ADO .Net Entity Framework</li>

            </ul>

        </div>

        <div class="col-md-4">
            <!-- Skills -->
            <strong>Operating Systems:</strong>
            <ul class="list-unstyled">
                <li>Mac OS X</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                        <span class="sr-only">90% Complete (success)</span>
                      </div>
                    </div>
                <li>UNIX</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete (success)</span>
                      </div>
                    </div>
                <li>Windows</li>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete (success)</span>
                      </div>
                    </div>
            </ul>

            <strong>Tools:</strong>
            <ul class="list-inline">
                <li>Visual Studio</li>
                <li>Microsoft SSMS</li>
                <li>Microsoft SSIS</li>
                <li>Splunk</li>
                <li>Version Control</li>
                <li>NetBeans</li>
                <li>Eclipse</li>
                <li>VIM</li>
                <li>Excel</li>
                <li>PyCharm</li>
                <li>PuTTY</li>
            </ul>

        </div>

    </div> <!-- End Row -->


    <div class="row">
        <div class="col-md-4">
            <h2 class="text-center">Education</h2>
            <ul class="list-unstyled">
                <li><strong>University of Pittsburgh</strong> Pittsburgh, PA  GPA: 3.07</li>
                <li></li>
                <li></li>
                <li>Graduated May 2014</li>
            </ul>
            <ul class="list-unstyled">
                <li><em>Bachelor of Science in Applied Mathematics</em></li>
                <li><em>Bachelor of Arts in Anthropology</em></li>
                <li><em>Minor in Computer Science</em></li>
            </ul>
        </div>

        <div class="col-md-4">
            <h2 class="text-center">Extra Activities</h2>
            <ul>
                <li>All American Wrestler in PA State Competition</li>
                <li>Ultramarathons, rowing, cycling, judo, water polo, wrestling</li>
                <li>President / Coach of the Wrestling Club, MEC Champion, NCWA National All American </li>
                <li>IRONMAN triathlete </li>
            </ul>

        </div>

        <div class="col-md-4">
            <h2 class="text-center">Civic Endevors</h2>
            <ul>
                <li>MS150 Ride for a Cure</li>
                <li>Higher Achievement – Teacher / Student Mentor</li>
                <li>Big Brother Big Sister</li>
                <li>“Eye to Eye” volunteer organization – local mentoring program</li>
                <li>Volunteer high school wrestling coach</li>
            </ul>
        </div>
    </div>
</div>



{% endblock %}

mysite/portfolio/templates/portfolio/self-help.html
{% extends "portfolio/base.html" %}
{% load staticfiles %}

{% block content %}

<div class="row">

    <div class="col-md-4">
        <div class="page-header">
            <h1>Self Help</h1>
        </div>

        <p class="lead">I created ServiceBaseV during my time at the service desk. Some content inside of ServiceBase
            is confidential so I cant demo it, however I can show the home page for the companies Self Help app
            which was modeled after my code and backed by the Microsoft SQL database I created.</p>

        <label>Tools:</label>
        <ul class="list-inline">
            <li>.Net Web Application</li>
            <li>Microsoft SQL Database</li>
            <li>JavaScript/jQuery</li>
            <li>Bootstrap CSS</li>
        </ul>
    </div>
    <div class="col-md-8">
        <img src="{% static 'portfolio/img/self-help.png' %}" class="img-responsive" alt="Responsive image">
    </div>

</div>



{% endblock %}